- name: Install nginx and run
  hosts: nginx
  become: yes
  tasks:
  - name: install nginx
    package:
      name: nginx
      state: present

  - name: start and enable
    service:
      name: nginx
      enabled: true
      state: restarted

