- name: Remove the default {{ component }} page
  ansible.builtin.file:
    path: "{{ app_path }}"
    state: absent
  igonre_errors: true

- name: Create {{ component }} directory
  ansible.builtin.file:
    path: "{{ app_path }}"
    state: directory

- name: Extract the {{ component }} code
  ansible.builtin.unarchive:
    src: "https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{ component }}-v2.zip"
    dest: "{{ app_path }}"
    remote_src: yes